### ISSUE TITLE
Application panicked

### ISSUE THREAD

**Issue by fgadaleta** [symmetree-labs/zerostash#132]
Trying to commit a large folder, application crashed ~70GB backup size

```
The application panicked (crashed).
Message:  range end index 4201359 out of range for slice of length 4194304
Location: libzerostash/src/objects.rs:226
```

**Comment by rsdy** [comment]
This can happen because there's no bounds check where writing -- essentially the deduplicator produces a too large chunk and that is not stopped from prapagating all the way to write. There are 2 things that would be helpful here: 

 * `0s-bench` should measure the largest and smallest chunks that are produced -- they should be around on average 8kB.
 * https://github.com/rsdy/zerostash/blob/master/libzerostash/src/rollsum.rs#L7 `BLOBBITS` controls the deduplication and when split happens -- by default the lower 13 bits is 0 is when split happens. You can change this parameter and see how it affects speed, compression, and crashes :)

I'm looking into issues like this at the moment, so it's very helpful! Thanks!

**Comment by rsdy** [comment]
@fgadaleta The latest master has a slightly adjusted version, that should produce smaller chunks. It also uses a tokio for work balancing, so you should not bottleneck on huge files. Let me know how it goes!

**Comment by fgadaleta** [comment]
> @fgadaleta The latest master has a slightly adjusted version, that should produce smaller chunks. It also uses a tokio for work balancing, so you should not bottleneck on huge files. Let me know how it goes!

ok will run it with the same conditions and will let you know. 
Thanks

**Comment by fgadaleta** [comment]
Ok same path and subfolders, same size, `0s` terminates with `all paths done` (though it doesn't really terminate, I had to kill it manually)
